### ISSUE TITLE
Generator : visual_studio_multi is not listed and other problems

### ISSUE THREAD

**Issue by dcube9** [bincrafters/conan-vs-extension#178]
Hi,
In VS Option Generator combobox list only **visual_studio**.
But I use **visual_studio_multi** in my project conanfile.txt : 
```
[requires]
benchmark/1.5.0

[generators]
visual_studio_multi

[options]
benchmark:shared=False
```
And installation directory is $(ProjectDir).conan

Drawnbacks of that  :
* conan-vs-extension create conanbuildinfo.props each time I move from Debug to Release and back and conanbuildinfo.props is override each time.
* conan-vs-extension modify project file and add <Import Project=".conan\conanbuildinfo.props" />, so I check-in and all developers cant use it because on open project cant find  ".conan\conanbuildinfo.props" (ignored from git)

I'm a newbe of conan's world and it possible I have made some mistake but what I want todo is add Debug and Release of win32 lib or dll in my project.

I build all library we need and I upload them in a common conan_server, so every developers dont need to build., only install.

Any solutions ?

Thks

**Comment by T-Deuty** [comment]
Hello,
I also experienced the issue "conan-vs-extension modify project file and add , so I check-in and all developers cant use it because on open project cant find ".conan\conanbuildinfo.props" (ignored from git)" but I have found a workaround in the meantime.

I go into detail on the workaround here: https://stackoverflow.com/questions/62581390/how-can-i-use-conan-to-both-provide-dependencies-for-the-visual-studio-ide-and-c

It is a bit further down in the "EDIT: Potential Workaround" section. Hope this helps in the meantime.
