### ISSUE TITLE
Add Support for 'msbuild' generator?

### ISSUE THREAD

**Issue by sully7** [bincrafters/conan-vs-extension#182]
As far as I can tell so far, the extension only supports the `visual_studio` generator. 

I think it would be extremely helpful if support was added for the (currently experimental) `[msbuild](https://docs.conan.io/en/latest/reference/generators/msbuild.html?highlight=msbuild)` generator. 

In my opinion, the `msbuild` generator has a _lot_ of added benefits (such as configuration-specific property sheets for individual dependencies), and makes a "VS _without_ cmake" environment much easier to work with.

This might also help fix issues such as:

- https://github.com/conan-io/conan-vs-extension/issues/178
- https://github.com/conan-io/conan-vs-extension/issues/137

Thoughts??

**Comment by memsharded** [comment]
Hi @sully7 

Thanks for the feedback. At the moment we don't plan to integrate this into the VS-extension, because it is experimental and a bit unstable. We are doing a ton of work to improve the integrations with the build system, not only the ``msbuild`` generator, but also there is a new ``MSBuildToolchain``, that goes with a new ``MSBuild`` command helper.

We need to stabilize all of this before considering integrating it in the extension, it might take a while, it requires a lot of work and we have many ongoing things. I suggest keeping an eye on the new tools and giving feedback if possible.

**Comment by sully7** [comment]
Makes sense to me!

As a side note, I've definitely been super happy with the attention the `MSBuild` environment has been receiving. Definitely all steps in the right direction, and extremely exciting stuff :)

Anyway, thanks for the quick feedback! I'll close out this issue for now.

Cheers!

**Comment by memsharded** [comment]
Thanks for the feedback!
