### ISSUE TITLE
Add "Conan -> Options" menu

### ISSUE THREAD

**Issue by SSE4** [bincrafters/conan-vs-extension#25]
it would be nice to jump straight to the conan options from the "Conan" menu.
need to find a way how to open specific settings dialog page.

**Comment by solvingj** [comment]
The initial version of the plugin had a Conan menu.  However, I felt this was awkward to maintain, and feel we are better of taking the same approach Microsoft took with `CMakeSettings.json`.   The most important thing users need to do in a project is map Visual Studio projects / configurations (configuration/platform/runtime) to Conan profiles or collections of settings (arch/build_type/runtime) .  This is almost identical to the situation with CMake.  I think we want to deal with as few dialogs as possible.  Perhaps later, we can have a "conan options" page which is a dialog box that effectively renders the JSON file in a window instead of a text editor.  Again, that's what CMake integration does now.  

https://devblogs.microsoft.com/cppblog/introducing-the-new-cmake-project-settings-ui/
