### ISSUE TITLE
Detect runtime library (MT vs MD vs MTd vs MDd)

### ISSUE THREAD

**Issue by SSE4** [bincrafters/conan-vs-extension#31]
it would be nice to automatically detect runtime library in use and apply to the conan command line `-s compiler.runtime=<runtime>`

**Comment by solvingj** [comment]
Yes. Of note, this might be tricky because of how the runtime is implemented in visual studio.  It was also tricky to enforce for the implementation of the `visual_studio` generator with Conan. 

On a related note, we also still have to allow the user to map custom Conan options/settings/profiles/etc to Visual Studio configurations, which we've resolved to do via the `.json` file.  If we cannot find a reasonable way to detect the runtime, it's not the end of the world.  Users can still set the value appropriately via the `.json` file.

**Comment by SSE4** [comment]
yep, in general, it always possible to specify things manually one way or another. ultimate goal is to make it working "out of the box", with as minimal interaction as possible.
