### ISSUE TITLE
Change generator from visual_studio_multi to just visual_studio

### ISSUE THREAD

**Issue by solvingj** [bincrafters/conan-vs-extension#7]
The standard `visual_studio` generator will be the preferred mechanism moving forward. Later we can add support for other generators, such as `visual_studio_multi`.

**Comment by SSE4** [comment]
any advantages of `visual_studio` generator? why is it preferred?

**Comment by solvingj** [comment]
yes, several. First, it's lazier. In order for `visual_studio_multi` to work, it has to download for all arch/configurations at once.  If you depend on boost, qt, or other big libraries, this is a huge penalty if you only need `x64/Release`.

**Comment by SSE4** [comment]
`visual_studio_multi` is also lazy. you may add needed configurations one by one, you don't need to install all artifacts at once.
in future we may decide to add setting to choose between `visual_studio_mutli` vs `visual_studio`, but I'd prefer to use `visual_studio_multi` as default.

**Comment by solvingj** [comment]
What is the advantage of multi?

**Comment by SSE4** [comment]
you don't have to deal with multiple props files per configurations, it's abstracted away - you just add single props file which has all conditions embedded in it.

**Comment by solvingj** [comment]
Let’s chat about it, I don’t think that actually provides any advantage when everything is automated in the plugin. I think it just makes it worse for a few reasons tbh.

**Comment by memsharded** [comment]
If the generated ``conanbuildinfo.props`` files are generated in different folders, and managed correctly, then it might be equivalent.

If the ``conanbuildinfo.props`` is overwritten because a new ``conan install`` is issued when the IDE changes configuration, then everything is broken, because caches become invalid, and it is necessary to re-build from scratch the new configuration. Incremental builds will error with very weird cases, linking with wrong artifacts (but without complaining/erroring directly)

**Comment by SSE4** [comment]
both `visual_studio` and `visual_studio_multi` are supported now
from the plug-in perspective, there is almost no difference in their usage
same from the user experience - it's completely transparent in both cases, user may not even know which generator is in use (or he might not be aware about the generator concept at all).
